[package]
name = "veilpass"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.14.0"
scarb-version = "2.14.0"

[dependencies]
starknet = "2.14.0"

[dev-dependencies]
snforge_std = "0.55.0"

[[target.starknet-contract]]
sierra = true
casm = true

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
